// Broadcast Atelier direction: the private entry is the quiet threshold into Kasha's secure editorial control room.
import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowUpRight, LockKeyhole, Moon, Sun } from "lucide-react";
import { useLocation } from "wouter";
import { useTheme } from "@/contexts/ThemeContext";
export { AdminDashboard } from "./AdminControlRoom";

export default function AdminLogin() {
  const [, setLocation] = useLocation(); const { theme, toggleTheme } = useTheme(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false);
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!email || !password) { setMessage("Enter both fields to continue."); return; } setMessage(""); setIsSubmitting(true); try { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 15000); let response: Response; try { response = await fetch("/api/firebase/session", { method: "POST", headers: { "content-type": "application/json", accept: "application/json" }, credentials: "include", signal: controller.signal, body: JSON.stringify({ email, password }) }); } finally { window.clearTimeout(timeout); } const contentType = response.headers.get("content-type") ?? ""; const rawBody = await response.text(); let result: { role?: string; error?: string } = {}; if (rawBody.trim() && contentType.includes("application/json")) { try { result = JSON.parse(rawBody) as { role?: string; error?: string }; } catch { throw new Error("The server returned an invalid login response. Please try again."); } } if (!response.ok) { if (response.status >= 500) throw new Error("The admin login service is temporarily unavailable. Please try again shortly."); throw new Error(result.error ?? "Invalid administrator email or password."); } if (result.role !== "admin") throw new Error("Administrator access was not granted."); setLocation("/admin/dashboard"); } catch (error: unknown) { if (error instanceof DOMException && error.name === "AbortError") setMessage("The login request timed out. Check your connection and try again."); else if (error instanceof TypeError) setMessage("Unable to reach the login service. Check your connection and try again."); else setMessage(error instanceof Error ? error.message : "Sign-in could not be completed."); } finally { setIsSubmitting(false); } };
  return <main className="admin-shell"><div className="admin-topbar"><a className="admin-back" href="/"><ArrowLeft size={15} /> Back to Kasha</a><button className="header-tool" type="button" onClick={toggleTheme} aria-label={`Switch to ${theme === "light" ? "dark" : "light"} mode`}>{theme === "light" ? <Moon size={16} /> : <Sun size={16} />}</button></div><section className="admin-card" aria-labelledby="admin-heading"><div className="admin-card-mark"><LockKeyhole size={20} /></div><p className="eyebrow">Kasha desk / private access</p><h1 id="admin-heading">Sign in to<br /><em>the desk.</em></h1><p className="admin-intro">Manage every public signal, field note, and future gathering from one quiet room.</p><form className="admin-form" onSubmit={handleSubmit}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@kashamultimedia.et" autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" autoComplete="current-password" /></label>{message && <p className="admin-error" role="alert">{message}</p>}<button className="button button-signal" type="submit" disabled={isSubmitting}>{isSubmitting ? "Verifying…" : "Enter the desk"} <ArrowUpRight size={16} /></button></form><p className="admin-note">The Kasha server verifies the administrator credentials before issuing a secure admin session.</p></section></main>;
}
